### PR TITLE
clean up source, call $apply, explicit ngInject handling

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@gajus noticed a few problems using your project with webpack, it seems that $apply isn't being called, and `/* @ngInject  */` directives are not applied for consumers of the npm module.

**Comment by graingert** [comment]
@marcelaraujo ping

**Comment by graingert** [comment]
@marcelaraujo @gajus ping ping

**Comment by graingert** [comment]
@marcelaraujo @gajus ping ping

**Comment by graingert** [comment]
@marcelaraujo @gajus ping ping ping ping

**Comment by marcelaraujo** [comment]
@graingert Why did you remove IIFE?

**Comment by graingert** [comment]
@marcelaraujo browserify adds an IIFE for you

**Comment by graingert** [comment]
@marcelaraujo I'm using this with my angular-swing2 fork on npm It hard codes swing to ~3.0.3 because 3.1 is broken.

**Pull request merged**
